services:
  - type: web
    name: breast-cancer-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /health